version: "3.9"

services:
  app:
    image: arneil/blurr-api:latest
    container_name: blurr-api
    env_file:
      - .env
    volumes:
      - /home/pc/var/app/blurr-api/.env:/app/.env
    ports:
      - 8000:8000
