name: Deploy app

on:
  push:
    tags:
      - v**-production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_NAMESPACE }}/blurr-api:latest .
          docker push ${{ secrets.DOCKER_NAMESPACE }}/blurr-api:latest

      - name: Deploy to Linux VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_NAMESPACE }}/blurr-api:latest
            docker-compose down
            docker-compose up -d
