name: Deploy app

on:
  push:
    tags:
      - v**-production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_NAMESPACE }}/blurr-api:latest .
          docker push ${{ secrets.DOCKER_NAMESPACE }}/blurr-api:latest

      - name: SSH to Server
        run: |
          mkdir ~/.ssh
          echo -e "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/ssh-key
          chmod 400 ~/.ssh/ssh-key
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh-key pc@${{ secrets.VM_HOST }} -p 2105 \
            'cd /home/pc/var/app/blurr-api && \
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && \
            sh deploy_production.sh'
